services:
  mongodb.localhost:
    image: mongo
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:${MONGO_PORT} --quiet
      interval: 5s
      retries: 10
      start_period: 5s
      timeout: 5s

  app.localhost:
    build:
      context: .
    depends_on:
      mongodb.localhost:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    # command: /bin/sh -c "while sleep 1000; do :; done" # only for debugging
