volumes:
  mongodb:
  mongodb_config:

services:
  mongodb.localhost:
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    build:
      context: ./mongodb_replica
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://${MONGO_HOST}:${MONGO_PORT} --quiet
      interval: 5s
      retries: 10
      start_period: 5s
      timeout: 5s

  app.localhost:
    build:
      context: .
    depends_on:
      mongodb.localhost:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    # command: /bin/sh -c "while sleep 1000; do :; done" # only for debugging
