# fly.toml app configuration file generated for booking on 2024-08-16T03:04:43+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'montel'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 4001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
